/**
 * Geographic label data for globe labels.
 * Curated list of countries (centroids) and major cities for on-globe text labels.
 * Each entry has: name, lat, lng, type ('country' | 'city'), and optional population rank.
 */

export interface GeoLabel {
  name: string;
  lat: number;
  lng: number;
  type: "country" | "city";
  /** 1 = largest/most important. Used for LOD filtering. */
  rank: number;
}

// ── Country labels (centroids / visual centers) ──
export const COUNTRY_LABELS: GeoLabel[] = [
  // North America
  { name: "United States", lat: 39.8, lng: -98.5, type: "country", rank: 1 },
  { name: "Canada", lat: 56, lng: -96, type: "country", rank: 1 },
  { name: "Mexico", lat: 23.6, lng: -102.5, type: "country", rank: 1 },
  { name: "Cuba", lat: 21.5, lng: -79.9, type: "country", rank: 2 },
  { name: "Guatemala", lat: 15.5, lng: -90.2, type: "country", rank: 3 },
  { name: "Honduras", lat: 14.7, lng: -86.2, type: "country", rank: 3 },
  { name: "Nicaragua", lat: 12.8, lng: -85.2, type: "country", rank: 3 },
  { name: "Costa Rica", lat: 10, lng: -84, type: "country", rank: 3 },
  { name: "Panama", lat: 8.5, lng: -80, type: "country", rank: 3 },
  { name: "Jamaica", lat: 18.1, lng: -77.3, type: "country", rank: 3 },
  { name: "Haiti", lat: 19, lng: -72.1, type: "country", rank: 3 },
  { name: "Dom. Rep.", lat: 18.7, lng: -70, type: "country", rank: 3 },

  // South America
  { name: "Brazil", lat: -14.2, lng: -51.9, type: "country", rank: 1 },
  { name: "Argentina", lat: -38.4, lng: -63.6, type: "country", rank: 1 },
  { name: "Colombia", lat: 4.6, lng: -74.1, type: "country", rank: 2 },
  { name: "Peru", lat: -9.2, lng: -75, type: "country", rank: 2 },
  { name: "Venezuela", lat: 6.4, lng: -66.6, type: "country", rank: 2 },
  { name: "Chile", lat: -35.7, lng: -71.5, type: "country", rank: 2 },
  { name: "Ecuador", lat: -1.8, lng: -78.2, type: "country", rank: 3 },
  { name: "Bolivia", lat: -16.3, lng: -63.6, type: "country", rank: 3 },
  { name: "Paraguay", lat: -23.4, lng: -58.4, type: "country", rank: 3 },
  { name: "Uruguay", lat: -32.5, lng: -55.8, type: "country", rank: 3 },
  { name: "Guyana", lat: 5, lng: -59, type: "country", rank: 3 },
  { name: "Suriname", lat: 4, lng: -56, type: "country", rank: 3 },

  // Europe
  { name: "United Kingdom", lat: 54, lng: -2, type: "country", rank: 1 },
  { name: "France", lat: 46.2, lng: 2.2, type: "country", rank: 1 },
  { name: "Germany", lat: 51.2, lng: 10.4, type: "country", rank: 1 },
  { name: "Spain", lat: 40.5, lng: -3.7, type: "country", rank: 1 },
  { name: "Italy", lat: 41.9, lng: 12.6, type: "country", rank: 1 },
  { name: "Poland", lat: 52, lng: 19.1, type: "country", rank: 2 },
  { name: "Ukraine", lat: 49, lng: 32, type: "country", rank: 2 },
  { name: "Romania", lat: 46, lng: 25, type: "country", rank: 2 },
  { name: "Netherlands", lat: 52.1, lng: 5.3, type: "country", rank: 2 },
  { name: "Belgium", lat: 50.5, lng: 4.5, type: "country", rank: 3 },
  { name: "Sweden", lat: 62, lng: 15, type: "country", rank: 2 },
  { name: "Norway", lat: 62, lng: 10, type: "country", rank: 2 },
  { name: "Finland", lat: 64, lng: 26, type: "country", rank: 2 },
  { name: "Denmark", lat: 56, lng: 10, type: "country", rank: 3 },
  { name: "Portugal", lat: 39.4, lng: -8.2, type: "country", rank: 2 },
  { name: "Greece", lat: 39, lng: 22, type: "country", rank: 2 },
  { name: "Czech Rep.", lat: 49.8, lng: 15.5, type: "country", rank: 3 },
  { name: "Austria", lat: 47.5, lng: 14.6, type: "country", rank: 3 },
  { name: "Switzerland", lat: 47, lng: 8.2, type: "country", rank: 3 },
  { name: "Hungary", lat: 47.2, lng: 19.5, type: "country", rank: 3 },
  { name: "Ireland", lat: 53.4, lng: -8, type: "country", rank: 2 },
  { name: "Serbia", lat: 44, lng: 21, type: "country", rank: 3 },
  { name: "Bulgaria", lat: 42.7, lng: 25.5, type: "country", rank: 3 },
  { name: "Croatia", lat: 45.1, lng: 16, type: "country", rank: 3 },
  { name: "Iceland", lat: 65, lng: -19, type: "country", rank: 3 },

  // Africa
  { name: "Nigeria", lat: 9.1, lng: 8.7, type: "country", rank: 1 },
  { name: "Egypt", lat: 26.8, lng: 30.8, type: "country", rank: 1 },
  { name: "South Africa", lat: -30.6, lng: 22.9, type: "country", rank: 1 },
  { name: "Algeria", lat: 28.3, lng: 1.7, type: "country", rank: 2 },
  { name: "Morocco", lat: 32, lng: -6, type: "country", rank: 2 },
  { name: "Ethiopia", lat: 9.1, lng: 40.5, type: "country", rank: 2 },
  { name: "Kenya", lat: -0.2, lng: 37.9, type: "country", rank: 2 },
  { name: "Tanzania", lat: -6.4, lng: 34.9, type: "country", rank: 2 },
  { name: "DR Congo", lat: -4.3, lng: 23.7, type: "country", rank: 2 },
  { name: "Libya", lat: 26.3, lng: 17.2, type: "country", rank: 2 },
  { name: "Sudan", lat: 15.4, lng: 32.3, type: "country", rank: 2 },
  { name: "Ghana", lat: 7.9, lng: -1.2, type: "country", rank: 3 },
  { name: "Mozambique", lat: -18.7, lng: 35.5, type: "country", rank: 3 },
  { name: "Madagascar", lat: -18.8, lng: 47.5, type: "country", rank: 2 },
  { name: "Angola", lat: -11.2, lng: 17.9, type: "country", rank: 3 },
  { name: "Tunisia", lat: 34, lng: 9.5, type: "country", rank: 3 },
  { name: "Senegal", lat: 14.5, lng: -14.5, type: "country", rank: 3 },
  { name: "Mali", lat: 17.6, lng: -4, type: "country", rank: 3 },
  { name: "Niger", lat: 17.6, lng: 8.1, type: "country", rank: 3 },
  { name: "Chad", lat: 15.5, lng: 18.7, type: "country", rank: 3 },
  { name: "Somalia", lat: 5, lng: 46.2, type: "country", rank: 3 },
  { name: "Namibia", lat: -22.6, lng: 17.1, type: "country", rank: 3 },
  { name: "Zambia", lat: -13.1, lng: 27.8, type: "country", rank: 3 },
  { name: "Zimbabwe", lat: -19, lng: 29.2, type: "country", rank: 3 },
  { name: "Uganda", lat: 1.4, lng: 32.3, type: "country", rank: 3 },

  // Asia
  { name: "China", lat: 35.9, lng: 104.2, type: "country", rank: 1 },
  { name: "India", lat: 20.6, lng: 79, type: "country", rank: 1 },
  { name: "Japan", lat: 36.2, lng: 138.3, type: "country", rank: 1 },
  { name: "Russia", lat: 62, lng: 105.3, type: "country", rank: 1 },
  { name: "Indonesia", lat: -0.8, lng: 113.9, type: "country", rank: 1 },
  { name: "Saudi Arabia", lat: 24, lng: 45, type: "country", rank: 2 },
  { name: "Iran", lat: 32.4, lng: 53.7, type: "country", rank: 2 },
  { name: "Turkey", lat: 39, lng: 35.2, type: "country", rank: 1 },
  { name: "Pakistan", lat: 30.4, lng: 69.3, type: "country", rank: 2 },
  { name: "Thailand", lat: 15.9, lng: 101, type: "country", rank: 2 },
  { name: "South Korea", lat: 36.5, lng: 127.8, type: "country", rank: 2 },
  { name: "Philippines", lat: 12.9, lng: 121.8, type: "country", rank: 2 },
  { name: "Vietnam", lat: 16, lng: 108, type: "country", rank: 2 },
  { name: "Iraq", lat: 33.2, lng: 43.7, type: "country", rank: 2 },
  { name: "Afghanistan", lat: 33.9, lng: 67.7, type: "country", rank: 3 },
  { name: "Malaysia", lat: 4.2, lng: 101.9, type: "country", rank: 2 },
  { name: "Myanmar", lat: 19.5, lng: 96.3, type: "country", rank: 3 },
  { name: "Nepal", lat: 28.4, lng: 84.1, type: "country", rank: 3 },
  { name: "Kazakhstan", lat: 48, lng: 67, type: "country", rank: 2 },
  { name: "Uzbekistan", lat: 41.4, lng: 64.6, type: "country", rank: 3 },
  { name: "Mongolia", lat: 46.9, lng: 103.8, type: "country", rank: 3 },
  { name: "Bangladesh", lat: 23.7, lng: 90.4, type: "country", rank: 2 },
  { name: "Sri Lanka", lat: 7.9, lng: 80.8, type: "country", rank: 3 },
  { name: "UAE", lat: 24, lng: 54, type: "country", rank: 3 },
  { name: "Israel", lat: 31.1, lng: 34.9, type: "country", rank: 3 },
  { name: "Syria", lat: 35, lng: 38, type: "country", rank: 3 },
  { name: "Cambodia", lat: 12.6, lng: 105, type: "country", rank: 3 },
  { name: "Laos", lat: 18, lng: 102.5, type: "country", rank: 3 },
  { name: "Taiwan", lat: 23.7, lng: 121, type: "country", rank: 3 },

  // Oceania
  { name: "Australia", lat: -25.3, lng: 133.8, type: "country", rank: 1 },
  { name: "New Zealand", lat: -40.9, lng: 174.9, type: "country", rank: 2 },
  { name: "Papua N.G.", lat: -6.3, lng: 143.9, type: "country", rank: 3 },
  { name: "Fiji", lat: -18, lng: 179, type: "country", rank: 3 },

  // Central Asia / Caucasus
  { name: "Georgia", lat: 42.3, lng: 43.4, type: "country", rank: 3 },
  { name: "Armenia", lat: 40.1, lng: 45, type: "country", rank: 3 },
  { name: "Azerbaijan", lat: 40.1, lng: 47.6, type: "country", rank: 3 },
];

// ── Major city labels ──
export const CITY_LABELS: GeoLabel[] = [
  // Rank 1: Global megacities (always visible when zoomed in enough)
  { name: "New York", lat: 40.71, lng: -74.01, type: "city", rank: 1 },
  { name: "London", lat: 51.51, lng: -0.13, type: "city", rank: 1 },
  { name: "Tokyo", lat: 35.68, lng: 139.69, type: "city", rank: 1 },
  { name: "Paris", lat: 48.86, lng: 2.35, type: "city", rank: 1 },
  { name: "Beijing", lat: 39.9, lng: 116.4, type: "city", rank: 1 },
  { name: "Moscow", lat: 55.76, lng: 37.62, type: "city", rank: 1 },
  { name: "São Paulo", lat: -23.55, lng: -46.63, type: "city", rank: 1 },
  { name: "Mumbai", lat: 19.08, lng: 72.88, type: "city", rank: 1 },
  { name: "Shanghai", lat: 31.23, lng: 121.47, type: "city", rank: 1 },
  { name: "Dubai", lat: 25.2, lng: 55.27, type: "city", rank: 1 },
  { name: "Sydney", lat: -33.87, lng: 151.21, type: "city", rank: 1 },
  { name: "Los Angeles", lat: 34.05, lng: -118.24, type: "city", rank: 1 },
  { name: "Cairo", lat: 30.04, lng: 31.24, type: "city", rank: 1 },
  { name: "Istanbul", lat: 41.01, lng: 28.98, type: "city", rank: 1 },
  { name: "Lagos", lat: 6.45, lng: 3.4, type: "city", rank: 1 },

  // Rank 2: Major world cities
  { name: "Berlin", lat: 52.52, lng: 13.4, type: "city", rank: 2 },
  { name: "Madrid", lat: 40.42, lng: -3.7, type: "city", rank: 2 },
  { name: "Rome", lat: 41.9, lng: 12.5, type: "city", rank: 2 },
  { name: "Chicago", lat: 41.88, lng: -87.63, type: "city", rank: 2 },
  { name: "Toronto", lat: 43.65, lng: -79.38, type: "city", rank: 2 },
  { name: "Mexico City", lat: 19.43, lng: -99.13, type: "city", rank: 2 },
  { name: "Buenos Aires", lat: -34.6, lng: -58.38, type: "city", rank: 2 },
  { name: "Rio de Janeiro", lat: -22.91, lng: -43.17, type: "city", rank: 2 },
  { name: "Seoul", lat: 37.57, lng: 127, type: "city", rank: 2 },
  { name: "Bangkok", lat: 13.76, lng: 100.5, type: "city", rank: 2 },
  { name: "Singapore", lat: 1.35, lng: 103.82, type: "city", rank: 2 },
  { name: "Hong Kong", lat: 22.32, lng: 114.17, type: "city", rank: 2 },
  { name: "Jakarta", lat: -6.2, lng: 106.85, type: "city", rank: 2 },
  { name: "New Delhi", lat: 28.61, lng: 77.21, type: "city", rank: 2 },
  { name: "Tehran", lat: 35.69, lng: 51.39, type: "city", rank: 2 },
  { name: "Nairobi", lat: -1.29, lng: 36.82, type: "city", rank: 2 },
  { name: "Johannesburg", lat: -26.2, lng: 28.04, type: "city", rank: 2 },
  { name: "Melbourne", lat: -37.81, lng: 144.96, type: "city", rank: 2 },
  { name: "Bogotá", lat: 4.71, lng: -74.07, type: "city", rank: 2 },
  { name: "Lima", lat: -12.05, lng: -77.04, type: "city", rank: 2 },
  { name: "Santiago", lat: -33.45, lng: -70.67, type: "city", rank: 2 },
  { name: "Amsterdam", lat: 52.37, lng: 4.9, type: "city", rank: 2 },
  { name: "Vienna", lat: 48.21, lng: 16.37, type: "city", rank: 2 },
  { name: "Warsaw", lat: 52.23, lng: 21.01, type: "city", rank: 2 },
  { name: "Stockholm", lat: 59.33, lng: 18.07, type: "city", rank: 2 },
  { name: "Lisbon", lat: 38.72, lng: -9.14, type: "city", rank: 2 },
  { name: "Athens", lat: 37.98, lng: 23.73, type: "city", rank: 2 },
  { name: "Riyadh", lat: 24.71, lng: 46.67, type: "city", rank: 2 },
  { name: "Ankara", lat: 39.93, lng: 32.86, type: "city", rank: 2 },
  { name: "Havana", lat: 23.11, lng: -82.37, type: "city", rank: 2 },

  // Rank 3: Important regional cities
  { name: "San Francisco", lat: 37.78, lng: -122.42, type: "city", rank: 3 },
  { name: "Miami", lat: 25.76, lng: -80.19, type: "city", rank: 3 },
  { name: "Houston", lat: 29.76, lng: -95.37, type: "city", rank: 3 },
  { name: "Seattle", lat: 47.61, lng: -122.33, type: "city", rank: 3 },
  { name: "Vancouver", lat: 49.28, lng: -123.12, type: "city", rank: 3 },
  { name: "Montreal", lat: 45.5, lng: -73.57, type: "city", rank: 3 },
  { name: "Barcelona", lat: 41.39, lng: 2.17, type: "city", rank: 3 },
  { name: "Munich", lat: 48.14, lng: 11.58, type: "city", rank: 3 },
  { name: "Milan", lat: 45.46, lng: 9.19, type: "city", rank: 3 },
  { name: "Prague", lat: 50.08, lng: 14.44, type: "city", rank: 3 },
  { name: "Budapest", lat: 47.5, lng: 19.04, type: "city", rank: 3 },
  { name: "Dublin", lat: 53.35, lng: -6.26, type: "city", rank: 3 },
  { name: "Brussels", lat: 50.85, lng: 4.35, type: "city", rank: 3 },
  { name: "Copenhagen", lat: 55.68, lng: 12.57, type: "city", rank: 3 },
  { name: "Oslo", lat: 59.91, lng: 10.75, type: "city", rank: 3 },
  { name: "Helsinki", lat: 60.17, lng: 24.94, type: "city", rank: 3 },
  { name: "Zurich", lat: 47.37, lng: 8.54, type: "city", rank: 3 },
  { name: "Osaka", lat: 34.69, lng: 135.5, type: "city", rank: 3 },
  { name: "Manila", lat: 14.6, lng: 120.98, type: "city", rank: 3 },
  { name: "Kuala Lumpur", lat: 3.14, lng: 101.69, type: "city", rank: 3 },
  { name: "Hanoi", lat: 21.03, lng: 105.85, type: "city", rank: 3 },
  { name: "Ho Chi Minh", lat: 10.82, lng: 106.63, type: "city", rank: 3 },
  { name: "Kolkata", lat: 22.57, lng: 88.36, type: "city", rank: 3 },
  { name: "Bangalore", lat: 12.97, lng: 77.59, type: "city", rank: 3 },
  { name: "Karachi", lat: 24.86, lng: 67.01, type: "city", rank: 3 },
  { name: "Dhaka", lat: 23.81, lng: 90.41, type: "city", rank: 3 },
  { name: "Addis Ababa", lat: 9.01, lng: 38.75, type: "city", rank: 3 },
  { name: "Accra", lat: 5.56, lng: -0.19, type: "city", rank: 3 },
  { name: "Casablanca", lat: 33.59, lng: -7.62, type: "city", rank: 3 },
  { name: "Cape Town", lat: -33.93, lng: 18.42, type: "city", rank: 3 },
  { name: "Dar es Salaam", lat: -6.79, lng: 39.28, type: "city", rank: 3 },
  { name: "Auckland", lat: -36.85, lng: 174.76, type: "city", rank: 3 },
  { name: "Perth", lat: -31.95, lng: 115.86, type: "city", rank: 3 },
  { name: "Denver", lat: 39.74, lng: -104.99, type: "city", rank: 3 },
  { name: "Atlanta", lat: 33.75, lng: -84.39, type: "city", rank: 3 },
  { name: "Medellín", lat: 6.25, lng: -75.56, type: "city", rank: 3 },
  { name: "Quito", lat: -0.18, lng: -78.47, type: "city", rank: 3 },
  { name: "Caracas", lat: 10.49, lng: -66.88, type: "city", rank: 3 },
  { name: "Montevideo", lat: -34.88, lng: -56.16, type: "city", rank: 3 },
  { name: "Reykjavik", lat: 64.15, lng: -21.94, type: "city", rank: 3 },
  { name: "Kyiv", lat: 50.45, lng: 30.52, type: "city", rank: 2 },
  { name: "Bucharest", lat: 44.43, lng: 26.1, type: "city", rank: 3 },
  { name: "Belgrade", lat: 44.79, lng: 20.45, type: "city", rank: 3 },
  { name: "Algiers", lat: 36.75, lng: 3.06, type: "city", rank: 3 },
  { name: "Doha", lat: 25.29, lng: 51.53, type: "city", rank: 3 },
  { name: "Abu Dhabi", lat: 24.45, lng: 54.65, type: "city", rank: 3 },
  { name: "Guangzhou", lat: 23.13, lng: 113.26, type: "city", rank: 3 },
  { name: "Chengdu", lat: 30.57, lng: 104.07, type: "city", rank: 3 },
  { name: "St. Petersburg", lat: 59.93, lng: 30.32, type: "city", rank: 3 },
];

/** All labels combined */
export const ALL_LABELS: GeoLabel[] = [...COUNTRY_LABELS, ...CITY_LABELS];
